export const GET_REQUEST_LIST = "GET_REQUEST_LIST";
export const GET_ADMIN_PENDING_REQUEST_LIST = "GET_ADMIN_PENDING_REQUEST_LIST";
export const GET_EDIT_REQUEST_DATA = "GET_EDIT_REQUEST_DATA";
export const GET_POLL_REQUEST_LIST = "GET_POLL_REQUEST_LIST";
export const GET_ADMIN_ASSIGN_REQUEST_LIST = "GET_ADMIN_ASSIGN_REQUEST_LIST";
export const GET_DESIGNER_ASSIGNED_REQUEST_LIST = "GET_DESIGNER_ASSIGNED_REQUEST_LIST";
export const GET_DESIGNER_ACTIVE_REQUEST_LIST = "GET_DESIGNER_ACTIVE_REQUEST_LIST";
export const DELIEVER_REQUEST_DATA = "DELIEVER_REQUEST_DATA";