export const LOG_IN='LOG_IN';
export const LOG_OUT='LOG_OUT';
export const SET_USER_TYPE='SET_USER_TYPE';
export const USER_UPDATE='USER_UPDATE';
export const PASSWORD_LINK='PASSWORD_LINK';
export const RESET_PASSWORD='RESET_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS='UPDATE_PASSWORD_SUCCESS';
export const GET_PROFILE_SUCCESS='GET_PROFILE_SUCCESS';